CREATE DATABASE IF NOT EXISTS db_autores;
CREATE DATABASE IF NOT EXISTS db_libros;
CREATE DATABASE IF NOT EXISTS db_categorias;
CREATE DATABASE IF NOT EXISTS db_prestamos;
CREATE DATABASE IF NOT EXISTS db_usuarios;
CREATE DATABASE IF NOT EXISTS db_generos;
CREATE DATABASE IF NOT EXISTS db_resennas;