spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: autores-microservice
              uri: ${AUTORES_SERVICE_URL:http://localhost:8084} # <-- Propiedad de entorno con respaldo local
              predicates:
                - Path=/api/autores/**
              filters:
                - AddResponseHeader=X-Gateway-Processed, True # <-- Filtro basico para la rúbrica

            - id: libros-microservice
              uri: ${LIBROS_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/api/libros/**
              filters:
                - AddResponseHeader=X-Gateway-Processed, True

            - id: categorias-microservice
              uri: ${CATEGORIAS_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/api/categorias/**
              filters:
                - AddResponseHeader=X-Gateway-Processed, True

            - id: prestamos-microservice
              uri: ${PRESTAMOS_SERVICE_URL:http://localhost:8089}
              predicates:
                - Path=/api/prestamos/**
              filters:
                - AddResponseHeader=X-Gateway-Processed, True

            - id: resennas-microservice
              uri: ${RESENNAS_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/resennas/**
              filters:
                - AddResponseHeader=X-Gateway-Processed, True

            - id: usuarios-microservice
              uri: ${USUARIOS_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/usuarios/**
              filters:
                - AddResponseHeader=X-Gateway-Processed, True

            - id: generos-microservice
              uri: ${GENEROS_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/generos/**
              filters:
                - AddResponseHeader=X-Gateway-Processed, True

            - id: multas-microservice
              uri: ${MULTAS_SERVICE_URL:http://localhost:8087}
              predicates:
                - Path=/api/v1/multas/**
              filters:
                - AddResponseHeader=X-Gateway-Processed, True

            - id: autenticacion-microservice
              uri: ${AUTENTICACION_SERVICE_URL:http://localhost:8088}
              predicates:
                - Path=/api/v1/auth/**,/api/v1/usuarios/**
              filters:
                - AddResponseHeader=X-Gateway-Processed, True

            - id: reservas-microservice
              uri: ${RESERVAS_SERVICE_URL:http://localhost:8090}
              predicates:
                - Path=/api/v1/reservas/**
              filters:
                - AddResponseHeader=X-Gateway-Processed, True


server:
  port: 8080