spring:
  application:
    name: autenticacion-microservice

  # Configuración de Base de Datos
  datasource:
    url: jdbc:mysql://localhost:3306/db_autenticacion
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuración de Migraciones con Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Configuración de Hibernate / JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

# Configuración del Servidor
server:
  port: 8088
  servlet:
    context-path: /api

# Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Configuracion de Logs
logging:
  level:
    org:
      springframework: INFO
    cl:
      duoc:
        autenticacion_microservice: DEBUG
  file:
    name: logs/autenticacion-microservice.log

#Configuracion Seguridad JWT
jwt:
  secret: a13644aa2a98114a0e84b4c35821263fd546c9e8fbeb73ccfc4dbbc68d530ed35bdd0df7ea742cd2c720ff20532addb20f1dbc092aa0636cae0da83b7ebcbc64
  expiration: 86400000