spring.application.name=usuarios-microservice

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/db_usuarios
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Server configuration
server.port=8081
server.servlet.context-path=/api

# Logging configuration
logging.level.org.springframework=INFO
logging.level.cl.duoc.dsy1103.usuarios_microservice=DEBUG
logging.file.name=logs/users-service.log

#JWT configuration
jwt.secret=d4edecce43f74efcc783364843bdbbeac712c68d8a6d3bdb8b1665ff79a59c427b9ad045582439158c8549bc4e71af087f4f5972d72ed827b8fa456b428ab4b2
