INSERT INTO categorias (nombre, descripcion, id_libro) VALUES
       ('Clásicos Universales', 'Obras literarias que han trascendido el tiempo y son fundamentales en la cultura global.', 1),
       ('Realismo Mágico', 'Género que introduce elementos fantásticos en un contexto narrativo realista y cotidiano.', 2),
       ('Literatura Contemporánea', 'Obras publicadas en la época actual que reflejan las problemáticas de la sociedad moderna.', 3),
       ('Novela Histórica', 'Relatos de ficción que se sitúan en un momento histórico real, respetando eventos y ambientes.', 4),
       ('Ciencia Ficción Distópica', 'Historias sobre sociedades futuras caracterizadas por el control totalitario o el desastre.', 5),
       ('Narrativa Psicológica', 'Obras centradas en el mundo interior, las emociones y los procesos mentales de los personajes.', 6),
       ('Literatura Juvenil', 'Libros dirigidos específicamente a lectores adolescentes con temáticas de crecimiento y aventura.', 7),
       ('Terror y Suspenso', 'Categoría enfocada en generar sensaciones de miedo, incertidumbre y tensión en el lector.', 8),
       ('Ensayo y Crítica', 'Textos en prosa donde el autor analiza, interpreta o evalúa un tema específico con rigor.', 9),
       ('Poesía Lírica', 'Composiciones que expresan la subjetividad y los sentimientos más profundos del autor.', 10),
       ('Fantasía Épica', 'Relatos que presentan mundos imaginarios con sus propias reglas, magias y héroes legendarios.', 11),
       ('Literatura Existencialista', 'Obras que exploran temas como la libertad individual, la angustia y el sentido de la vida.', 12),
       ('Novela Negra', 'Subgénero policial que aborda el mundo del crimen y la justicia desde una perspectiva cruda.', 13),
       ('Literatura de Vanguardia', 'Escritos que buscan romper con las estructuras tradicionales y experimentar con la forma.', 14),
       ('Biografía y Memoria', 'Relatos detallados sobre la vida de personas reales, escritos por ellos mismos o por terceros.', 15),
       ('Literatura Regionalista', 'Obras que resaltan las costumbres, el lenguaje y la identidad de una zona geográfica particular.', 16),
       ('Cuento Corto', 'Narraciones breves que se enfocan en una sola trama o incidente con gran intensidad.', 17),
       ('Dramaturgia', 'Textos escritos con el propósito de ser representados en un escenario teatral.', 18),
       ('Literatura de Viajes', 'Relatos que documentan las experiencias y descubrimientos del autor al explorar nuevos lugares.', 19),
       ('Filosofía y Pensamiento', 'Textos dedicados a la reflexión sobre el conocimiento, la ética y la naturaleza humana.', 20);