INSERT INTO categorias (nombre, descripcion) VALUES
     ('Terror', 'Obras que buscan inducir miedo o pavor en el lector.'),
     ('Realismo Mágico', 'Integración de elementos fantásticos en un entorno real.'),
     ('Fantasía Épica', 'Narrativas en mundos imaginarios con elementos mágicos.'),
     ('Ciencia Ficción', 'Basada en avances científicos y tecnológicos hipotéticos.'),
     ('Novela Policial', 'Centrada en la resolución de un crimen o misterio.'),
     ('Poesía', 'Expresión de la belleza o sentimiento a través del verso.'),
     ('Drama', 'Obras con conflictos emocionales y situaciones tensas.'),
     ('Ensayo', 'Reflexión literaria sobre un tema específico.'),
     ('Biografía', 'Historia de la vida de una persona real.'),
     ('Aventura', 'Viajes peligrosos y eventos emocionantes.'),
     ('Clásicos', 'Obras consagradas que perduran en el tiempo.'),
     ('Romance', 'Historias centradas en relaciones amorosas.'),
     ('Suspenso', 'Diseñadas para mantener al lector en incertidumbre.'),
     ('Histórica', 'Relatos ambientados en periodos del pasado real.'),
     ('Humor', 'Escritos destinados a entretener y divertir.'),
     ('Misterio', 'Obras que requieren resolver un enigma.'),
     ('Gótico', 'Combina elementos de terror y romance oscuro.'),
     ('Fábula', 'Relatos breves con una enseñanza o moraleja.'),
     ('Distopía', 'Sociedades ficticias indeseables o catastróficas.'),
     ('Filosofía', 'Textos que exploran el pensamiento y la existencia.');