spring.application.name=reservas-microservice

# Configuración de URLs de Microservicios Remotos
services.usuarios.baseUrl=http://localhost:8081/api/usuarios
services.libros.baseUrl=http://localhost:8082/api/libros