INSERT INTO autor (nombre_completo, biografia, nacionalidad, fecha_nacimiento) VALUES
       ('Gabriel García Márquez', 'Escritor colombiano, premio Nobel de Literatura en 1982 y autor de Cien años de soledad.', 'Colombiana', '1927-03-06'),
       ('Isabel Allende', 'Escritora chilena, autora de superventas como La casa de los espíritus.', 'Chilena', '1942-08-02'),
       ('Jorge Luis Borges', 'Destacado escritor argentino de cuentos, ensayos y poemas, clave en la literatura del siglo XX.', 'Argentina', '1899-08-24'),
       ('Miguel de Cervantes', 'Autor de Don Quijote de la Mancha, considerada la primera novela moderna.', 'Española', '1547-09-29'),
       ('Virginia Woolf', 'Escritora británica, figura destacada del modernismo literario y el feminismo.', 'Británica', '1882-01-25'),
       ('Ernest Hemingway', 'Escritor y periodista estadounidense, ganador del Premio Nobel y del Pulitzer.', 'Estadounidense', '1899-07-21'),
       ('Franz Kafka', 'Escritor checo en lengua alemana, cuya obra es pionera en la literatura del absurdo.', 'Austriaca', '1883-07-03'),
       ('Haruki Murakami', 'Escritor japonés contemporáneo conocido por sus relatos surrealistas y melancólicos.', 'Japonesa', '1949-01-12'),
       ('Gabriela Mistral', 'Poeta chilena y la primera mujer latinoamericana en recibir el Nobel de Literatura.', 'Chilena', '1889-04-07'),
       ('Julio Cortázar', 'Escritor e intelectual argentino, maestro del relato corto y la narrativa innovadora.', 'Argentina', '1914-08-26'),
       ('Fyodor Dostoevsky', 'Novelista ruso que exploró la psicología humana en el contexto político de su país.', 'Rusa', '1821-11-11'),
       ('Chimamanda Ngozi Adichie', 'Escritora nigeriana contemporánea, autora de Americanah y reconocida feminista.', 'Nigeriana', '1977-09-15'),
       ('Mario Vargas Llosa', 'Escritor peruano, uno de los más importantes novelistas y ensayistas contemporáneos.', 'Peruana', '1936-03-28'),
       ('Oscar Wilde', 'Escritor, poeta y dramaturgo irlandés, famoso por su ingenio y mordacidad.', 'Irlandesa', '1854-10-16'),
       ('Simone de Beauvoir', 'Escritora y filósofa existencialista francesa, autora de El segundo sexo.', 'Francesa', '1908-01-09'),
       ('Edgar Allan Poe', 'Escritor estadounidense, maestro del relato corto de terror y la novela policiaca.', 'Estadounidense', '1809-01-19'),
       ('Elena Ferrante', 'Seudónimo de una novelista italiana conocida por su exitosa saga napolitana.', 'Italiana', '1943-04-05'),
       ('José Saramago', 'Escritor portugués, ganador del Nobel de Literatura en 1998.', 'Portuguesa', '1922-11-16'),
       ('Clarice Lispector', 'Escritora brasileña de origen ucraniano, considerada una de las más importantes del siglo XX.', 'Brasileña', '1920-12-10'),
       ('Victor Hugo', 'Escritor romántico francés, autor de clásicos como Los Miserables.', 'Francesa', '1802-02-26');