INSERT INTO autores (nombre_completo, biografia, nacionalidad, fecha_nacimiento) VALUES
     ('Stephen King', 'Escritor estadounidense de novelas de terror y suspenso.', 'Estadounidense', '1947-09-21'),
     ('Gabriel García Márquez', 'Célebre escritor colombiano, premio Nobel de Literatura.', 'Colombiano', '1927-03-06'),
     ('Isabel Allende', 'Escritora chilena, reconocida por sus obras de realismo mágico.', 'Chilena', '1942-08-02'),
     ('J.K. Rowling', 'Autora británica de la famosa saga de Harry Potter.', 'Británica', '1965-07-31'),
     ('George R.R. Martin', 'Escritor de la épica saga Canción de Hielo y Fuego.', 'Estadounidense', '1948-09-20'),
     ('Haruki Murakami', 'Escritor y traductor japonés de fama mundial.', 'Japonés', '1949-01-12'),
     ('Miguel de Cervantes', 'Autor de la obra cumbre Don Quijote de la Mancha.', 'Español', '1547-09-29'),
     ('Jorge Luis Borges', 'Escritor argentino, clave en la literatura en español.', 'Argentino', '1899-08-24'),
     ('Julio Cortázar', 'Escritor e intelectual argentino, autor de Rayuela.', 'Argentino', '1914-08-26'),
     ('Agatha Christie', 'Famosa escritora británica de novelas policiales.', 'Británica', '1890-09-15'),
     ('Mario Vargas Llosa', 'Escritor peruano, premio Nobel de Literatura.', 'Peruano', '1936-03-28'),
     ('Pablo Neruda', 'Poeta chileno, uno de los más grandes del siglo XX.', 'Chileno', '1904-07-12'),
     ('Ernest Hemingway', 'Escritor estadounidense y periodista.', 'Estadounidense', '1899-07-21'),
     ('Virginia Woolf', 'Escritora británica, figura del modernismo literario.', 'Británica', '1882-01-25'),
     ('Franz Kafka', 'Escritor bohemio cuya obra es icónica en el siglo XX.', 'Checo', '1883-07-03'),
     ('Oscar Wilde', 'Poeta y dramaturgo irlandés.', 'Irlandés', '1854-10-16'),
     ('Edgar Allan Poe', 'Escritor estadounidense de cuentos de terror.', 'Estadounidense', '1809-01-19'),
     ('Jane Austen', 'Autora británica de clásicos como Orgullo y Prejuicio.', 'Británica', '1775-12-16'),
     ('H.P. Lovecraft', 'Escritor de horror cósmico.', 'Estadounidense', '1890-08-20'),
     ('Marcel Proust', 'Autor francés de En busca del tiempo perdido.', 'Francés', '1871-07-10');